apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: project-expense
  region: us-east-1

managedNodeGroups:
  - name: project-expense
    instanceTypes: [c3.large]
    desiredCapacity: 3
    spot: true